name: Deploy ASP.NET Core API to IIS

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish API
      run: dotnet publish ./DeploymentAPI/DeploymentAPI.csproj -c Release -o ./publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-build
        path: ./publish



  deploy:

    needs: build
    runs-on: self-hosted

    steps:

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: api-build
        path: C:\deploy\api

    - name: Stop IIS Website
      shell: powershell
      run: |
        Import-Module WebAdministration
        Stop-WebSite -Name "AutoDeploySite"

    - name: Deploy files to IIS folder
      shell: powershell
      run: |
        Copy-Item "C:\deploy\api\*" "D:\AutoDeploy" -Recurse -Force

    - name: Start IIS Website
      shell: powershell
      run: |
        Import-Module WebAdministration
        Start-WebSite -Name "AutoDeploySite"
